### PR TITLE
Simplified webpack build

### PR DESCRIPTION
**Pull request by scytacki**
It is an attempt to simplify the portal-pages build. It removes webpack compiling from build.js and index.js
It uses `webpack-serve` to provide a fast dev experience with the examples folder.
In dev mode the css is not separate from the portal-pages javascript. This should provide the fastest dev experience.   However in several dev scenarios it is necessary to have a separate css, so that is supported too.

### CODE REVIEW

**Comment by scytacki** [comment]
This is ready to merge now. Hopefully the new setup makes sense. I tried to update the README to explain how to use the various local servers for development.  So I'd recommend reading it to see what you think: https://github.com/concord-consortium/portal-pages/blob/simplified-webpack-build/README.md

**Comment by dougmartin** [comment]
@scytacki The changes look good.  I ran all the npm scripts under Windows to ensure they ran (which they did) but `npm run lint` fixed up two files automatically so I went ahead and added a commit to save those fixes.

@knowuh, @pjanik - You should probably do the approvals since I added a commit.

**Comment by pjanik** [comment]
It looks good to me. I'm still not familiar with some parts of this repo (server etc.), but the simplified build process is great.

**Comment by scytacki** [comment]
One thing that didn't work quite as I expected is the extraction of the css from the portal-report components.  I haven't spent much time on it, but the portal-report.js library still has the css in it. So it injects two style elements on the page when it is loaded. I was thinking the rule that used mini-css-extract-plugin would have pulled the css out of this too. But it didn't. 

I tried adding a `less` to the list of file extensions processed by webpack in portal-pages but that didn't help. So I'm guessing there more configuration on portal-report or portal-pages to enable this. Or perhaps it is not currently possible.

It does make me wonder how npm libraries that have image assets work when built by webpack. Perhaps the generally approach is to inline them with `data` urls.

**Comment by knowuh** [comment]
The README changes made sense to me.  Just by reading the README however, I didn't get a good sense for what the differences were between production and dev builds. 

I find the issues around asset loading to always be confusing. I belive @pjanik has done deep investigations on this in the past.  From @scytacki 's most recent comment, it sounds like the library builds and runs fine in the portal but is injecting styles into the document.  I feel like this might be acceptable for the short term.

Otherwise, this works great for developers, so I am happy with it.  👍

**Pull request merged**
