### PR TITLE
Update to React 16.9.0 [#172782876]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by kswenson** [comment]
>Also I'm not sure how maintainable many of these enzyme tests will be.

FYI, [React Testing Library](https://testing-library.com/docs/react-testing-library/intro#this-solution) is an alternative approach to unit testing React components that directly addresses the fragility of tests question.

**Comment by scytacki** [comment]
@kswenson I was reading about that last night after seeing these enzyme tests. Do we use it anywhere already?

**Comment by kswenson** [comment]
The slate-editor library uses it, although the tests are still fairly rudimentary.

**Comment by dougmartin** [comment]
I think checking the full html in these form components is the best way to go.  Granted the test fails on a small change but why the changed html is updated in the test the diff shows the change.

**Comment by dougmartin** [comment]
@scytacki this now passes the rigse cucumber tests so I've set it ready for review.

**Pull request merged**
