### PR TITLE
Obtain subject area or grade level params from URL query string to su…

### PR DESCRIPTION
**Pull request by jsimpson-cc**
…pport redirects to the STEM finder.

[#150519376]

EDIT deleted comment and example no longer relevant.

### CODE REVIEW

**Comment by jsimpson-cc** [comment]
Example redirect URL and scroll to finder:

http://localhost:3000/?grade-level=middle-school#portal-pages-finder

**Comment by scytacki** [comment]
This approach seems generally good.
It would be better if could handle URLs like this:
https://learn.concord.org/stem-resources/subject/biology
https://learn.concord.org/stem-resources/grade-level/elementary-school

The portal already has a special stem-resources handler that is used for opening resource lightboxes directly.  So it could be updated to handle `stem-resources/subject/...` and `stem-resources/grade-level/...` as well.
In these cases it would just render the home page.

Then the same code you have now would be run.  The only differences is that the `PortalPages.getQueryParams()` would be updated to parse the different url form. Since they aren't really query params, it might be better to change the method to `getFiltersFromURL()`. This could return a object just like the current params object. So it would have keys for subject and grade-level.

**Comment by jsimpson-cc** [comment]
Sure that makes sense. I'll rework the URL format. 
I'm wondering though with the current approach (passing in the filters to the renderStemFinder() call) this requires the client caller to first call `PortalPages.getFiltersFromURL()` .
And this code typically lives in admin settings custom Home Page Content, requiring the author to make the additional API call. Does it make sense to do this URL parsing inside of the PortalPages API impl, or inside the StemFinder component (maybe in getInitialState()?)

**Comment by scytacki** [comment]
Yeah I think it makes sense to put it in the StemFinder component, so the author doesn't need to do the extra call. You might still want to provide a way to manually set the filters as properties to StemFinder component, that would make testing easier. 

What we'll probably want to do eventually is to setup ReactRouter so that when the filters are changed then URL will be changed too. So then this might all be handled by ReactRouter. I'm not familiar with that though, so I think it is best to stick with the approach above for now.

**Comment by jsimpson-cc** [comment]
Since I'm looking in this area and trying not to break functionality that was just added: 
Using the /stem-resources/ route to test a bad material type or id, I see that "Resource Not Found" is set as the page title like I would expect. The home page renders, but it is blurred, not responsive to anything and there is no other message.

Looking at the code
```
    else
      @lightbox_resource = nil
    end
    if @lightbox_resource
      @lightbox_resource = materials_data([@lightbox_resource], nil, 4).shift()
      @page_title = @lightbox_resource[:name]
    else
      @page_title = "Resource not found"
    end
    @auto_show_lightbox_resource = true

    homePage = HomePage.new(current_visitor, current_settings)
    load_notices
    load_featured_materials
    render :home, locals: homePage.view_options, layout: homePage.layout, status: @lightbox_resource.nil? ? 404: 200
  end


```

I'm wondering, is the intention to set `@auto_show_lightbox_resource = true` only if `@lightbox_resource` is non nil?

**Comment by jsimpson-cc** [comment]
Though making that change results in the home page being rendered normally but with the title "Resource Not Found" and the garbage type or id in the URL. Not sure if that's what we want either.

**Comment by scytacki** [comment]
My guess is that if `@auto_show_lightbox_resource = true`, and `@lightbox_resource` is nil. Then the portal-pages code should render a blurred background with a lightbox saying the resource couldn't be found.  Perhaps some changes to the lightboxes broke this behavior (or it never worked). I'll make a new bug story about this.

**Comment by scytacki** [comment]
Here is the story: https://www.pivotaltracker.com/story/show/150714464

**Pull request merged**
